---
- name: ensure prometheus data directory owner is nobody
  become: yes
  file:
        path: "{{ prometheus_volume_source}}"
        owner: nobody
        mode: 0777 
        state: directory 
  notify: 
    - Restart prometheus container
    - Restart grafana container

- name: Copy config file
  become: yes
  template:
        src: prometheus.yml.j2
        dest: "{{ prometheus_volume_source}}/prometheus.yml"
        owner: root
        mode: 0666 
  notify: 
    - Restart prometheus container
    - Restart grafana container

- name: Start prometheus container
  become: yes
  docker_container:
    name: "{{ prometheus_container_name }}"
    hostname: "{{ prometheus_container_name }}"
    image: "{{ prometheus_image }}"
    networks:
            - name: devops_net
    command: "{% for key in prometheus_commandline_args %}--{{key}}={{prometheus_commandline_args[key]}} {% endfor %}"
    #    published_ports:
    #      - 9090:9090
    volumes:
      - "{{ prometheus_volume_mountinstruction }}" 
    restart_policy: always


    
